image: woahbase/alpine-quasar 

pages:
  cache:
    paths:
      - app/node_modules/
  script:
    - cd app/ 
    - npm install
    - quasar build
  artifacts:
    paths:
      - app/dist/spa 
  only:
    - master
