image: node:10.15.0

pages:
  cache:
    paths:
      - node_modules/
  script:
    - cd app/ 
    - npm install
    - quasar build
  artifacts:
    paths:
      - /app/dist/spa 
  only:
    - master
