version: '3.7'
services:
  kori_front:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - './app:/app'
    command: /bin/sh -c "yarn install && quasar dev"
